### ISSUE TITLE
SIGPIPE kills mailexporter silently

### ISSUE THREAD

**Issue by joker234** [cherti/mailexporter#13] opened 2016-12-01 23:29 UTC
see also issue here: https://github.com/prometheus/prometheus/issues/2241

**Comment by cherti** [comment] 2016-12-21 11:34
Can you give more context on the circumstances? I cannot reproduce the behavior here, even with `killall -PIPE mailexporter`, which makes fixing a little difficult.

**Comment by joker234** [comment] 2017-01-18 18:10
With the actual version I cannot reproduce too. Maybe better stall this issue and wait for further bugs about that.

**Comment by cherti** [comment] 2017-01-18 19:38
Alright, closing then for now.

**Closed as completed by cherti** 2017-01-18 19:38 UTC
Labels: bug, cannot reproduce
